version: '3.3'

services:    
  
  mytestdb:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'mytestdb'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql

    networks:
     - backend

  web:
    build: .
    command: python mysite/manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/code
    ports:
      - "8001:8001"
    depends_on:
      - mytestdb
    links:
      - mytestdb
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_USER: 'root'
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_ROOT_PASSWORD='password'
      # - MYSQL_USER: 'root'
    restart: always
    ports:
      - 8082:80
    volumes:
      - /sessions

# Names our volume
volumes:
  my-db:

networks:
  backend:
    driver: bridge